<?php
/**
 * Implements hook_disable().
 *
 * Remove field from node bundle (content type) and then delete the field.
 */
function demo_field_disable() {
	$ctype = $form_state['values']['efcb_contenttype'];
  $instance = array(
    'field_name' => 'efcb_attach_form',
    'entity_type' => 'node',
    'bundle' => $ctype,
  );
  field_delete_instance($instance);
  field_delete_field($instance['field_name']);
  print 'Removed ' . $instance['field_name'] . "\n";
}